### ISSUE TITLE
Error on /tpa c

### ISSUE THREAD

**Issue by ndv400** [RestoreMonarchyPlugins/Teleportation#4]
```
[08.12.2019 13:50:51] [Info] [World] [Admin] Art [Arte^^ka]: "/tpa c"
[08.12.2019 13:51:01] [Error] An error occured while executing tpa [c]: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.Player.UnturnedPlayer.get_CharacterName () [0x00000] in <7270128d00524688a0793f5e4981226f>:0 
  at Rocket.Unturned.Player.UnturnedPlayer.get_DisplayName () [0x00000] in <7270128d00524688a0793f5e4981226f>:0 
  at RestoreMonarchy.Teleportation.Utils.TeleportationRequestHelper.CancelTPARequest (RestoreMonarchy.Teleportation.TeleportationPlugin plugin, Rocket.Unturned.Player.UnturnedPlayer caller) [0x0004e] in <d8910d6716104ae3aea972f157185c76>:0 
  at RestoreMonarchy.Teleportation.Commands.TPACommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x0009b] in <d8910d6716104ae3aea972f157185c76>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <466fa14d466749559a64a11ae8acbc60>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x001b2] in <466fa14d466749559a64a11ae8acbc60>:0 

```

**Comment by Trojaner** [comment]
You are trying to teleport to player who isnt online

**Comment by RestoreMonarchy** [comment]
I just published a pre-release, because I don't have time to test the plugin I ask you to try it out. 
It should remove all requests of a player when he disconnects either if he's sender or target.
Please reply to me under this issue if it works or not. Download release from [here](https://github.com/RestoreMonarchyPlugins/Teleportation/releases/tag/1.0.2.1-beta)

Thanks!

**Comment by ndv400** [comment]
Hmm, still having some errors. Different ones, though. Newest version of everything installed. @RestoreMonarchy 
With this plugin:
```
[27.12.2019 1:35:29] [Info] [Игрок] Ameliei [Ameliei] bled to death!
[27.12.2019 1:35:29] [Info] Player finished session: 76561198399266485
[27.12.2019 1:37:15] [Info] Broadcast: [Игрок] Ameliei disconnected from the server.
[27.12.2019 1:37:15] [Error] Error in MulticastDelegate PlayerDisconnected: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at RestoreMonarchy.Teleportation.Utils.TeleportationRequestHelper.ClearPlayerRequests (RestoreMonarchy.Teleportation.TeleportationPlugin plugin, Steamworks.CSteamID steamID) [0x0004a] in <40b238c922dc4501ac4bd64d66809ba0>:0 
  at RestoreMonarchy.Teleportation.TeleportationPlugin.OnPlayerDisconnected (Rocket.Unturned.Player.UnturnedPlayer player) [0x00008] in <40b238c922dc4501ac4bd64d66809ba0>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00019] in <466fa14d466749559a64a11ae8acbc60>:0 
```

JoinLeaveMessages (your version that has the functionality of showing which country the player's joining from that I really like):
```
[27.12.2019 11:34:18] [Info] Connecting: PlayerID: 76561198883601080 Name: Nuclear Шрык Character: [Игрок] Артём Москов
[27.12.2019 11:34:18] [Error] Error in MulticastDelegate PlayerConnected: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.WebException: Error getting response stream (ReadDone2): ReceiveFailure ---> System.Exception:   at System.Net.WebConnection.HandleError (System.Net.WebExceptionStatus st, System.Exception e, System.String where) [0x00000] in <d2957de1c3fd4781a43d89572183136c>:0 
  at System.Net.WebConnection.ReadDone (System.IAsyncResult result) [0x00000] in <d2957de1c3fd4781a43d89572183136c>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x00000] in <d2957de1c3fd4781a43d89572183136c>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Net.WebConnection.HandleError (System.Net.WebExceptionStatus st, System.Exception e, System.String where) [0x0003b] in <d2957de1c3fd4781a43d89572183136c>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x00072] in <d2957de1c3fd4781a43d89572183136c>:0 
  at System.Net.WebClient.DownloadString (System.Uri address) [0x00020] in <d2957de1c3fd4781a43d89572183136c>:0 
  at System.Net.WebClient.DownloadString (System.String address) [0x00016] in <d2957de1c3fd4781a43d89572183136c>:0 
  at JoinLeaveMessages.JoinLeaveMessages.CountryMessage (Rocket.Unturned.Player.UnturnedPlayer player) [0x0002a] in <cf731de3283047cd8d7df4a7e9107a5d>:0 
  at JoinLeaveMessages.JoinLeaveMessages.Events_OnPlayerConnected (Rocket.Unturned.Player.UnturnedPlayer player) [0x00012] in <cf731de3283047cd8d7df4a7e9107a5d>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00019] in <466fa14d466749559a64a11ae8acbc60>:0 
```
And MoreHomes still breaks after doing /rocket reload:
```
[29.12.2019 13:25:55] [Error] Value cannot be null.
Parameter name: source
[29.12.2019 13:25:55] [Error]   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0000d] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.GetPlayer (System.Collections.Generic.List`1[T] data, System.UInt64 playerId) [0x0000e] in <866b081215954d21997e3c00a39cdc7c>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.GetBedsCount (System.Collections.Generic.List`1[T] data, System.UInt64 playerId) [0x00001] in <866b081215954d21997e3c00a39cdc7c>:0 
  at RestoreMonarchy.MoreHomes.Patches.BarricadeManager_AskClaimBed_Patch.AskClaimBed_Prefix (SDG.Unturned.BarricadeManager __instance, Steamworks.CSteamID steamID, System.Byte x, System.Byte y, System.UInt16 plant, System.UInt16 index) [0x00153] in <866b081215954d21997e3c00a39cdc7c>:0 
  at (wrapper dynamic-method) SDG.Unturned.BarricadeManager.askClaimBed_Patch2(object,Steamworks.CSteamID,byte,byte,uint16,uint16)
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
[29.12.2019 13:25:55] [Error] Exception has been thrown by the target of an invocation.

```

**Comment by RestoreMonarchy** [comment]
Alright, so I fixed Teleportation error in v1.0.2.2

I'm not really gonna fix MoreHomes for now, but please create a seperate issue for it [here](https://github.com/RestoreMonarchyPlugins/MoreHomes/issues) make a title:
> Plugin breaks after rocket reload
Please in the description include some logs, this error and detailed description then sooner I'm gonna fix it

JoinLeaveMessages seems like web API is down or something, so it should surely start working again. I'm gonna update it to avoid such errors and just not display the country if web api is done, but also add support for other web apis in case one was offline.
